### ISSUE TITLE
libdarknet.so: cannot open shared object file:

### ISSUE THREAD

**Issue by MattiasMM** [lianghyv/Mini_Yolov3#1]
Error cannot open shared object.

Steps to recreate
1. it clone the repo
2. pip install flask
3. make 
4. python restful_server.py
```
Traceback (most recent call last):
  File "restful_server.py", line 61, in <module>
    net = Net()
  File "restful_server.py", line 22, in __init__
    lib = CDLL("libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libdarknet.so: cannot open shared object file: No such file or directory

```

with python 3:
```

python3 restful_server.py 
Traceback (most recent call last):
  File "restful_server.py", line 1, in <module>
    import flask
ImportError: No module named 'flask'

```

**Comment by MattiasMM** [comment]
By following the instructions for installing flask for python 3 on this [forum](https://stackoverflow.com/questions/10763440/how-to-install-python3-version-of-package-via-pip-on-ubuntu) the error with python 3 too is:


```
python3 restful_server.py 
Traceback (most recent call last):
  File "restful_server.py", line 61, in <module>
    net = Net()
  File "restful_server.py", line 22, in __init__
    lib = CDLL("libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libdarknet.so: cannot open shared object file: No such file or directory
```

**Comment by lianghyv** [comment]
you need move the shared library to /lib or check LD_LIBRARY_PATH
